### ISSUE TITLE
Localize the "Ninja Skin" DLC

### ISSUE THREAD

**Issue by dmitmel** [dmitmel/crosscode-ru-ng#5]
@L-Sherry Do you have any ideas about approaching this? I was writing an email to you about this, but I guess I'll summarize my thoughts in this thread tomorrow.

**Comment by L-Sherry** [comment]
I don't have the DLC. What's in there to localize ? The only thing I know is item 498.

**Comment by L-Sherry** [comment]
I don't have any DLC, so i made my own:

`assets/extension/post-game-dlc/post-game-dlc.json`:
```
{
        "name": {
                "de_DE": "Die Nachspiel DLC",
                "en_US": "The Postgame DLC"
        },
        "description": {
                "en_US": "Discover what happens to Lea after Sergey dies in the epilogue !",
                "de_DE": "Entdecken was wird Lea stattfinden nachdem des Sergeys Tod in der epilog !<<C<< 4/20 du dummkopf"
        }
}
```

And a translation pack for it (sorry, playing MRB does not make me speak russian):
```
{
        "extension/post-game-dlc/post-game-dlc.json/name": {
                "orig":"The Postgame DLC",
                "text":"Le DLC d'après-jeu"
        },
        "extension/post-game-dlc/post-game-dlc.json/description": {
                "orig":"Discover what happens to Lea after Sergey dies in the epilogue !",
                "text":"Découvrez ce que Lea se mange après que Sergey crève dans l'épilogue !"
        }
}
```

And with the latest patch that i pushed in Localize-Me, this seems to work. It should be enough to translate any DLC.

If that works, tell me, so i can bump the version and make a new release.

**Comment by dmitmel** [comment]
What about translating mods? Do you intend to make another path prefix for them?

**Comment by L-Sherry** [comment]
If mods "install" stuff in assets/data/, i should be able to translate them already, provided they get loaded via jquery like the game does.

(well, except for a deadlock which cannot really be fixed if mods block in their postload until their resources are loaded)

**Comment by dmitmel** [comment]
Alright, another question. Why did you choose to limit localizable files to just the `assets/data/` directory? Also, you perform a check whether the path starts with `data/`. Hashmap lookup (I hope that objects or at least `Map`s are implemented as hashmaps internally) won't be much slower to check whether the map file contains a translation pack for the requested file.

**Comment by L-Sherry** [comment]
Historical reasons, I guess.

But what else would you want to localize anyway ? `data/` and `extension/` are pretty much the only directories that can contain localizable json files. Well, except for `mods/`, but directory names in there are arbitrary, so that cannot work (and let's not talk about ccmods).

And yes, checking for the expected prefix is a good thing to do before stripping it out. I don't only check for `"data/"`, i check for `ig.root + "data/"`.

**Comment by dmitmel** [comment]
Done, this will be added in v1.0.6
