### ISSUE TITLE
Бесконечная загрузка

### ISSUE THREAD

**Issue by EugVV** [dmitmel/crosscode-ru-ng#6]
После обновления до v1.0.6 застревает на экране "Loading Game", прогресс бар останавливается, совсем немного не дойдя до конца. С v1.0.5 такой проблемы нет.
Игра GOG, 1.2.0-5, Linux, DLC стоит.

**Comment by dmitmel** [comment]
Другие моды установленны? Без DLC повторяется? При обновлении старые папки удалили (маловероятно, что это как-то повлияет, но всё же)?

Если на все вопросы ответ "нет", то тогда выполните, пожалуйста, поставьте nw.js SDK. Вот как это сделать в случае Windows (если у Вас не он установлен, то я могу тоже описать инструкцию):

1. Скачайте архив <https://dl.nwjs.io/v0.35.5/nwjs-sdk-v0.35.5-win-x64.zip> (64-битный) или <https://dl.nwjs.io/v0.35.5/nwjs-sdk-v0.35.5-win-ia32.zip> (32-битный).
2. Распакуйте прямо в папку игры с заменой файлов.
3. Удалите файл `CrossCode.exe`.
4. Переименуйте файл `nw.exe` в `CrossCode.exe`
5. Запускайте игру, установку SDK-версии можно проверить нажатием F12. Если всё установлено правильно - то откроется инструмент разработчика chrome.

После установки запустите КроссКод, откройте консоль разработчика, переключитесь на вкладку "Console". Если там отобразились какие-то ошибки (красные или жёлтые сообщение) - то пришлите скриншотом либо текстом. Если ошибок нет: в тот момент, когда прогресс-бар зависает, выполните следующее в консоли:

```js
modloader.frame.contentWindow.ig.resources
```

или, если выражение выше даст ошибку:

```js
ig.resources
```

Если отобразится непустой список - пожалуйста, пришлите скриншотом результат:

```js
modloader.frame.contentWindow.ig.resources.map(r => `${r.cacheType} ${r.path}`)
```

или опять таки без `modloader.frame.contentWindow.`, если то не сработает.

А вообще, странно довольно. У меня DLC тоже стоит, для разработки модов игру по сто раз в день запускаю и такую ошибку не наблюдаю.

**Comment by dmitmel** [comment]
Ой ой ой. У Вас же Linux. Пардон, не заметил. В инструкции по установке nw.js SDK скачайте <https://dl.nwjs.io/v0.35.5/nwjs-symbol-v0.35.5-linux-x64.tar.gz> или <https://dl.nwjs.io/v0.35.5/nwjs-symbol-v0.35.5-linux-ia32.tar.gz>, при удалении удаляйте просто `CrossCode` и переименовывайте `nw` в `CrossCode`. Может понадобится `chmod +x CrossCode`.

**Comment by dmitmel** [comment]
Ещё можно не париться и установить nw из терминала:

```sh
cd path/to/CrossCode
curl -Lf 'https://dl.nwjs.io/v0.35.5/nwjs-sdk-v0.35.5-linux-x64.tar.gz' | tar -xzvf - --strip-components=1
mv -fv nw CrossCode
```

**Comment by EugVV** [comment]
Поставил с нуля без DLC - стартует с v1.0.6.
Установил DLC - точно так же застревает.
В консоли [такое](https://drive.google.com/file/d/1kYeKLW4kAjuv8gv4wDLilW27FGQ6hpYQ/view?usp=sharing).

**Comment by dmitmel** [comment]
Какой документ по ссылке на гугл-диск? У меня нету доступа на просмотр.

**Comment by EugVV** [comment]
Забыл включить доступ, сейчас должно быть видно.

**Comment by dmitmel** [comment]
А можете ещё, пожалуйста, выполнить в консоли

```js
modloader.frame.contentWindow.ig.resources.map(r => `${r.cacheType} ${r.path}`)
```

и отправить файл `assets/extension/ninja-skin/ninja-skin.json`? Я, конечно, не знаю, будут ли против открытой публикации этого файла разработчики, так что лучше либо по электронной почте, либо на том же гугл-диске с ограниченным доступом.

P.S. гитхаб позволяет прикреплять изображения к комментариям.

**Comment by EugVV** [comment]
Файл выслал. А команда выдаёт такой массив:
[0 … 99]
0: "PlayerConfig shizuka"
1: "PlayerConfig shizuka0"
2: "PlayerConfig emilie"
3: "PlayerConfig sergey"
4: "PlayerConfig schneider"
5: "PlayerConfig schneider2"
6: "PlayerConfig hlin"
7: "PlayerConfig grumpy"
8: "PlayerConfig buggy"
9: "PlayerConfig glasses"
10: "PlayerConfig apollo"
11: "PlayerConfig joern"
12: "PlayerConfig triblader1"
13: "Character main.sergey"
14: "Character main.emilie"
15: "Character main.glasses"
16: "Character antagonists.fancyguy"
17: "Character antagonists.sidekick"
18: "Character misc.radical-fish"
19: "Character main.schneider"
20: "WebAudioBuffer media/sound/arena/applause-short-01.ogg"
21: "WebAudioBuffer media/sound/arena/round-start-swoosh.ogg"
22: "WebAudioBuffer media/sound/arena/round-end-swoosh.ogg"
23: "AnimationSheet player-poses"
24: "WebAudioBuffer media/bgm/ability-got.mp3"
25: "Character main.schneider2"
26: "Image media/face/lea-hand.png"
27: "Character main.shizuka"
28: "Character main.guild-leader"
29: "Character main.grumpy"
30: "Image media/face/lea-special.png"
31: "Character main.buggy"
32: "Character greenies.female-researcher"
33: "WebAudioBuffer media/sound/battle/enemies/fish-scream.ogg"
34: "undefined NO_PATCH"
35: "WebAudioBuffer media/sound/hud/landmark-discovery.mp3"
36: "Extension ninja-skin"
37: "AnimationSheet shizuka"
38: "WebAudioBuffer media/sound/battle/special/shizuka-3-end-2933.ogg"
39: "AnimationSheet enemies.seahorse"
40: "AnimationSheet npc.guild-leader"
41: "EffectSheet combat.pentafist"
42: "AnimationSheet npc.grumpy"
43: "AnimationSheet npc.buggy"
44: "AnimationSheet npc.sidekick"
45: "Character party-tmp.triblader-1"
46: "AnimationSheet npc.triblader-1"
47: "Image media/entity/player/poses.png "
48: "Image media/entity/player/poses.png"
49: "Image media/entity/player/move-shizuka.png"
50: "Image media/entity/player/throw-shizuka.png"
51: "Image media/entity/player/shizuka-special.png"
52: "Image media/entity/balls/default.png "
53: "Image media/entity/balls/default.png  "
54: "Image media/entity/balls/default.png   "
55: "AnimationSheet npc.emilie"
56: "EffectSheet enemies.jungle"
57: "Image media/entity/enemy/seahorse.png"
58: "AnimationSheet npc.schneider"
59: "Image media/entity/npc/guild-leader.png "
60: "Image media/entity/effects/pentafist-punch.png"
61: "WebAudioBuffer media/sound/battle/sweep-short-hi.ogg"
62: "WebAudioBuffer media/sound/battle/sweep-hi.ogg"
63: "Image media/entity/npc/grumpy.png"
64: "Image media/entity/npc/buggy.png"
65: "EffectSheet combat.hexacast"
66: "AnimationSheet npc.glasses"
67: "Image media/entity/npc/sidekick.png"
68: "Image media/face/avatars-new.png"
69: "Image media/entity/npc/triblader.png"
70: "Image media/entity/npc/runners.png"
71: "Image media/entity/npc/triblader-battle.png"
72: "Image media/face/programmer.png"
73: "Image media/face/emilie.png"
74: "Image media/face/glasses.png"
75: "Image media/face/fancyguy.png"
76: "Image media/face/sidekick.png"
77: "Image media/face/other.png"
78: "Image media/face/schneider.png"
79: "Image media/face/shizuka.png"
80: "Image media/face/guild-leader.png"
81: "Image media/face/grumpy.png"
82: "Image media/face/buggy.png"
83: "Image media/face/tulips.png"
84: "Image media/entity/npc/emilie.png"
85: "Image media/entity/npc/emilie-attack.png"
86: "Image media/entity/npc/schneider.png "
87: "Image media/entity/npc/schneider.png"
88: "Image media/entity/npc/glasses.png"
89: "AnimationSheet npc.fancyguy"
90: "Image media/entity/npc/fancyguy.png "
91: "Image media/entity/npc/fancyguy.png"
92: "WebAudioBuffer media/sound/battle/rock-debris1.ogg"
93: "WebAudioBuffer media/sound/battle/rock-burst1.ogg"
94: "WebAudioBuffer media/sound/battle/enemies/parrot/parrot-gun-loop.ogg"
95: "WebAudioBuffer media/sound/battle/enemies/parrot/parrot-gun-tail.ogg"
96: "WebAudioBuffer media/sound/environment/pot-destructable.ogg"
97: "WebAudioBuffer media/sound/battle/enemies/sweep.ogg"
98: "WebAudioBuffer media/sound/battle/sweep-short.ogg"
99: "WebAudioBuffer media/sound/battle/enemies/electrical.ogg"
[100 … 121]
100: "WebAudioBuffer media/sound/battle/enemies/shokat/shokat-shocked-short.ogg"
101: "WebAudioBuffer media/sound/battle/enemies/shokat/shokat-hiss.ogg"
102: "WebAudioBuffer media/sound/battle/thud-2.ogg"
103: "WebAudioBuffer media/sound/battle/enemies/sloth/sloth-moan-3.ogg"
104: "WebAudioBuffer media/sound/battle/thud-4.ogg"
105: "WebAudioBuffer media/sound/battle/enemies/sloth/sloth-moan-2.ogg"
106: "WebAudioBuffer media/sound/battle/enemies/chicken/chicken-01.ogg"
107: "WebAudioBuffer media/sound/battle/enemies/chicken/chicken-02.ogg"
108: "WebAudioBuffer media/sound/battle/charge-03.ogg"
109: "WebAudioBuffer media/sound/battle/charge-04.ogg"
110: "WebAudioBuffer media/sound/scenes/sweep.ogg"
111: "WebAudioBuffer media/sound/background/dungeons/shock-generator.ogg"
112: "WebAudioBuffer media/sound/battle/slime-splash-1.ogg"
113: "WebAudioBuffer media/sound/battle/blubb-2.ogg"
114: "WebAudioBuffer media/sound/boss/wave-boss/wave-blob-appear.ogg"
115: "WebAudioBuffer media/sound/boss/wave-boss/wave-boss-draw-start.ogg"
116: "WebAudioBuffer media/sound/battle/throw.ogg"
117: "WebAudioBuffer media/sound/battle/wave-swell-3.ogg"
118: "WebAudioBuffer media/sound/scenes/swoosh-fall-short.ogg"
119: "WebAudioBuffer media/sound/boss/whale/whale-call-3.ogg"
120: "WebAudioBuffer media/sound/battle/sweep-even-longer.ogg"
121: "WebAudioBuffer media/sound/boss/whale/whale-call.ogg"
length: 122

**Comment by dmitmel** [comment]
> Файл выслал. А команда выдаёт такой массив:

А это после того момента, как загрузка зависает?

**Comment by EugVV** [comment]
> А это после того момента, как загрузка зависает?

Да.

**Comment by dmitmel** [comment]
Короче говоря. Руки только сейчас добрались до дебаггера (утром и днём был занят), но я довольно сильно поржал с этого бага (за репорт спасибо), в итоге оказалось, что проблема в CCLoader'е. Баг можно воспроизвести только установкой скомпилированного мода (со странички релизов), поэтому я и не заметил его при разработке. Я пока пойду чинить CCLoader, а пока фикса не написан, можно выполнить следующую команду из директории КроссКода в качестве временной заплатки:

```
mv assets/mods/crosscode-ru/assets/ru-translation-tool assets
```

**Comment by dmitmel** [comment]
Баг исправлен, я загрузил новые архивы в тот же релиз.
